### ISSUE TITLE
Registing SLIP-0044 

### ISSUE THREAD

**Issue by serisia** [xpc-wg/xpchain#80]
We want to regist coin type (BIP-44).
After internal discussion, I used 398 in [CCWallet](https://github.com/serisia/CCWallet/tree/xpc-testing).

Now, XPC is published and stable.
I'm going to make PR for below document.

https://github.com/satoshilabs/slips/blob/master/slip-0044.md

**Comment by serisia** [comment]
I fork the repository into xpc-wg and add XPChain.
https://github.com/xpc-wg/slips/blob/slip44/xpc/slip-0044.md

I will make a PR around tomorrow.

**Comment by moochannel** [comment]
I checked the entry 398 is free and no PR to book the entry 398 is there.
But I'm concerned about another coin has received commented to `Use the first free entry` in other PR(540).

**Comment by serisia** [comment]
Well, I think I will explain the background of our situation.
Thanks for your advice.

**Comment by serisia** [comment]
Completed.
XPC's index is 398.
